name: liquid_dart
description: Liquid template engine for Dart and Flutter, compatible with LiquidJS 10.24.0 and Shopify-style templates.
version: 1.0.1
repository: https://github.com/jeremycochard/liquid_dart

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
